-- ==============================================================================
-- ĐỒ ÁN: HỆ THỐNG QUẢN LÝ NHÂN SỰ (EMS) - BẢO MẬT CƠ SỞ DỮ LIỆU
-- SCRIPT 01: KHỞI TẠO USER, CẤP QUYỀN VÀ CẤU TRÚC LƯỢC ĐỒ 8 BẢNG
-- SERVICE NAME MẶC ĐỊNH: FREEPDB1
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- PHẦN I: KHỞI TẠO USER VÀ CẤP QUYỀN HỆ THỐNG
-- LƯU Ý: ĐOẠN NÀY BẮT BUỘC PHẢI CHẠY BẰNG TÀI KHOẢN 'SYS AS SYSDBA' VÀO 'FREEPDB1'
-- ------------------------------------------------------------------------------

-- 1. Tạo User Quản trị dự án (Schema chính)
CREATE USER EMS_ADMIN IDENTIFIED BY "EmsPassword2026";

-- 2. Cấp quyền kết nối, quản trị và khởi tạo đối tượng cơ bản
GRANT CONNECT, RESOURCE, DBA TO EMS_ADMIN;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE TRIGGER, CREATE PROCEDURE TO EMS_ADMIN;
ALTER USER EMS_ADMIN QUOTA UNLIMITED ON USERS;

-- 3. Cấp đặc quyền sử dụng các Package bảo mật hệ thống (Cho VPD, Redaction, FGA)
GRANT EXECUTE ON DBMS_RLS TO EMS_ADMIN;     -- Virtual Private Database
GRANT EXECUTE ON DBMS_REDACT TO EMS_ADMIN;  -- Data Redaction
GRANT EXECUTE ON DBMS_FGA TO EMS_ADMIN;     -- Fine-Grained Auditing
GRANT CREATE ANY CONTEXT TO EMS_ADMIN;      -- Application Context

-- 4. Cấp đặc quyền quản trị chính sách Oracle Label Security (Sử dụng chuẩn Role LBAC_DBA)
ALTER SESSION SET CONTAINER = CDB$ROOT;
ALTER PLUGGABLE DATABASE FREEPDB1 CLOSE IMMEDIATE;
ALTER PLUGGABLE DATABASE FREEPDB1 OPEN;
ALTER SESSION SET CONTAINER = FREEPDB1;
GRANT LBAC_DBA TO EMS_ADMIN;
GRANT EXECUTE ON SA_COMPONENTS TO EMS_ADMIN;
GRANT EXECUTE ON SA_USER_ADMIN TO EMS_ADMIN;
GRANT EXECUTE ON SA_LABEL_ADMIN TO EMS_ADMIN;
GRANT EXECUTE ON SA_POLICY_ADMIN TO EMS_ADMIN;
GRANT EXECUTE ON SA_SESSION TO EMS_ADMIN;

-- ------------------------------------------------------------------------------
-- PHẦN II: KHỞI TẠO LƯỢC ĐỒ CƠ SỞ DỮ LIỆU LÕI (8 BẢNG)
-- LƯU Ý: ĐOẠN NÀY BẮT BUỘC PHẢI CHẠY BẰNG TÀI KHOẢN LÀ 'EMS_ADMIN' VỪA TẠO
-- ------------------------------------------------------------------------------

-- 1. Bảng Danh mục Phòng Ban
CREATE TABLE PHONG_BAN (
    MaPB VARCHAR2(10) PRIMARY KEY,
    TenPB VARCHAR2(100) NOT NULL
);

-- 2. Bảng Danh mục Nhóm quyền Ứng dụng
CREATE TABLE APP_ROLES (
    Role_Name VARCHAR2(50) PRIMARY KEY,
    Description VARCHAR2(255)
);

-- 3. Bảng Hồ sơ Nhân Viên (Gốc gánh VPD, Redaction, Trigger, FGA)
CREATE TABLE NHAN_VIEN (
    MaNV VARCHAR2(20) PRIMARY KEY,
    HoTen VARCHAR2(100) NOT NULL,
    NgaySinh DATE,
    SDT VARCHAR2(15),
    Luong NUMBER(15, 2),
    MaSoThue VARCHAR2(20),
    MaPB VARCHAR2(10),
    CONSTRAINT fk_nv_pb FOREIGN KEY (MaPB) REFERENCES PHONG_BAN(MaPB)
);

-- 4. Bảng Tài khoản Người dùng Hệ thống
CREATE TABLE APP_USERS (
    ID_User VARCHAR2(20) PRIMARY KEY,
    Username VARCHAR2(50) UNIQUE NOT NULL,
    Password VARCHAR2(255) NOT NULL, -- Lưu trữ chuỗi mã hóa bcrypt từ Backend
    Role_Name VARCHAR2(50),
    MaNV VARCHAR2(20),
    CONSTRAINT fk_usr_role FOREIGN KEY (Role_Name) REFERENCES APP_ROLES(Role_Name),
    CONSTRAINT fk_usr_nv FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV)
);

-- 5. Bảng Thông tin Dự Án (Thực thể gánh cấu phần bảo mật nhãn OLS)
CREATE TABLE DU_AN (
    MaDA VARCHAR2(20) PRIMARY KEY,
    TenDA VARCHAR2(200) NOT NULL,
    NganSach NUMBER(18, 2),
    NgayBatDau DATE,
    TrangThai VARCHAR2(50)
    -- Cột nhãn OLS (Label column) sẽ do Oracle tự động bổ sung sau khi gán Policy
);

-- 6. Bảng Phân Công Nhân Sự Vào Dự Án (Gánh chính sách VPD nâng cao qua Join)
CREATE TABLE PHAN_CONG (
    MaNV VARCHAR2(20),
    MaDA VARCHAR2(20),
    VaiTro VARCHAR2(100),
    SoGioThamGia NUMBER(5, 2),
    PRIMARY KEY (MaNV, MaDA),
    CONSTRAINT fk_pc_nv FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV),
    CONSTRAINT fk_pc_da FOREIGN KEY (MaDA) REFERENCES DU_AN(MaDA)
);

-- 7. Bảng Nhật Ký Chấm Công Định Kỳ (Gánh chính sách VPD mở rộng tách biệt dòng)
CREATE TABLE CHAM_CONG (
    MaChamCong VARCHAR2(20) PRIMARY KEY,
    MaNV VARCHAR2(20),
    NgayLamViec DATE NOT NULL,
    TrangThai VARCHAR2(50), -- Trạng thái: Có mặt, Vắng, Trễ
    CONSTRAINT fk_cc_nv FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV)
);

-- 8. Bảng Lưu Vết Lịch Sử Biến Động Lương (Đích đến của Trigger Nghiệp vụ)
CREATE TABLE LICH_SU_LUONG (
    MaLichSu NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaNV VARCHAR2(20),
    LuongCu NUMBER(15, 2),
    LuongMoi NUMBER(15, 2),
    NgayDoi TIMESTAMP DEFAULT SYSTIMESTAMP,
    NguoiThucHien VARCHAR2(50), -- Lưu trữ ID định danh của người thực hiện cập nhật
    CONSTRAINT fk_lsl_nv FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV)
);

-- Xác nhận lưu trữ toàn bộ cấu trúc lược đồ dữ liệu vật lý
COMMIT;