CREATE USER EMS_ADMIN IDENTIFIED BY "EmsPassword2026";

GRANT CONNECT, RESOURCE, DBA TO EMS_ADMIN;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE TRIGGER, CREATE PROCEDURE TO EMS_ADMIN;
ALTER USER EMS_ADMIN QUOTA UNLIMITED ON USERS;

GRANT EXECUTE ON DBMS_RLS TO EMS_ADMIN;     
GRANT EXECUTE ON DBMS_REDACT TO EMS_ADMIN; 
GRANT EXECUTE ON DBMS_FGA TO EMS_ADMIN;     
GRANT CREATE ANY CONTEXT TO EMS_ADMIN;     

ALTER SESSION SET CONTAINER = CDB$ROOT;
ALTER PLUGGABLE DATABASE FREEPDB1 CLOSE IMMEDIATE;
ALTER PLUGGABLE DATABASE FREEPDB1 OPEN;
ALTER SESSION SET CONTAINER = FREEPDB1;

GRANT LBAC_DBA TO EMS_ADMIN;
GRANT EXECUTE ON SA_COMPONENTS TO EMS_ADMIN;
GRANT EXECUTE ON SA_USER_ADMIN TO EMS_ADMIN;
GRANT EXECUTE ON SA_LABEL_ADMIN TO EMS_ADMIN;
GRANT EXECUTE ON SA_POLICY_ADMIN TO EMS_ADMIN;
GRANT EXECUTE ON SA_SESSION TO EMS_ADMIN;